version: "2"

services:
  
  samba:
    image: dperson/samba
    environment:
      - TZ=America/Argentina/Buenos_Aires
    command: '-u "usuario;password" -s "tl3;/tl3;yes;no;no" -S'
    stdin_open: true
    tty: true
    ports:
      - 8139:139
      - 8145:445
    volumes:
      - ${PWD}:/tl3
